/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AdRequestWeights = factory(root.Dynamix.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AdRequestWeights model module.
   * @module model/AdRequestWeights
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>AdRequestWeights</code>.
   * @alias module:model/AdRequestWeights
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>AdRequestWeights</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdRequestWeights} obj Optional instance to populate.
   * @return {module:model/AdRequestWeights} The populated <code>AdRequestWeights</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('adSizeInfo')) {
        obj['adSizeInfo'] = ApiClient.convertToType(data['adSizeInfo'], 'Number');
      }
      if (data.hasOwnProperty('adRestrictions')) {
        obj['adRestrictions'] = ApiClient.convertToType(data['adRestrictions'], 'Number');
      }
      if (data.hasOwnProperty('publisherLocationInfo')) {
        obj['publisherLocationInfo'] = ApiClient.convertToType(data['publisherLocationInfo'], 'Number');
      }
      if (data.hasOwnProperty('timeInfo')) {
        obj['timeInfo'] = ApiClient.convertToType(data['timeInfo'], 'Number');
      }
      if (data.hasOwnProperty('publisherHistoryInfo')) {
        obj['publisherHistoryInfo'] = ApiClient.convertToType(data['publisherHistoryInfo'], 'Number');
      }
      if (data.hasOwnProperty('monetaryRequirementInfo')) {
        obj['monetaryRequirementInfo'] = ApiClient.convertToType(data['monetaryRequirementInfo'], 'Number');
      }
      if (data.hasOwnProperty('impressionInfo')) {
        obj['impressionInfo'] = ApiClient.convertToType(data['impressionInfo'], 'Number');
      }
      if (data.hasOwnProperty('internetInfo')) {
        obj['internetInfo'] = ApiClient.convertToType(data['internetInfo'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} adSizeInfo
   */
  exports.prototype['adSizeInfo'] = undefined;
  /**
   * @member {Number} adRestrictions
   */
  exports.prototype['adRestrictions'] = undefined;
  /**
   * @member {Number} publisherLocationInfo
   */
  exports.prototype['publisherLocationInfo'] = undefined;
  /**
   * @member {Number} timeInfo
   */
  exports.prototype['timeInfo'] = undefined;
  /**
   * @member {Number} publisherHistoryInfo
   */
  exports.prototype['publisherHistoryInfo'] = undefined;
  /**
   * @member {Number} monetaryRequirementInfo
   */
  exports.prototype['monetaryRequirementInfo'] = undefined;
  /**
   * @member {Number} impressionInfo
   */
  exports.prototype['impressionInfo'] = undefined;
  /**
   * @member {Number} internetInfo
   */
  exports.prototype['internetInfo'] = undefined;



  return exports;
}));


