/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AdRestrictions = factory(root.Dynamix.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AdRestrictions model module.
   * @module model/AdRestrictions
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>AdRestrictions</code>.
   * @alias module:model/AdRestrictions
   * @class
   * @param videoAllowed {Boolean} 
   */
  var exports = function(videoAllowed) {
    var _this = this;


    _this['videoAllowed'] = videoAllowed;


  };

  /**
   * Constructs a <code>AdRestrictions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdRestrictions} obj Optional instance to populate.
   * @return {module:model/AdRestrictions} The populated <code>AdRestrictions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('restrictedKeywords')) {
        obj['restrictedKeywords'] = ApiClient.convertToType(data['restrictedKeywords'], ['String']);
      }
      if (data.hasOwnProperty('videoAllowed')) {
        obj['videoAllowed'] = ApiClient.convertToType(data['videoAllowed'], 'Boolean');
      }
      if (data.hasOwnProperty('validSlotLengthsInMilliseconds')) {
        obj['validSlotLengthsInMilliseconds'] = ApiClient.convertToType(data['validSlotLengthsInMilliseconds'], ['Number']);
      }
      if (data.hasOwnProperty('vastEnabled')) {
        obj['vastEnabled'] = ApiClient.convertToType(data['vastEnabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Keywords represent words that would describe an image after doing image analysis.
   * @member {Array.<String>} restrictedKeywords
   */
  exports.prototype['restrictedKeywords'] = undefined;
  /**
   * @member {Boolean} videoAllowed
   */
  exports.prototype['videoAllowed'] = undefined;
  /**
   * List of slot lengths in milliseconds that are valid for this sink.
   * @member {Array.<Number>} validSlotLengthsInMilliseconds
   */
  exports.prototype['validSlotLengthsInMilliseconds'] = undefined;
  /**
   * @member {Boolean} vastEnabled
   */
  exports.prototype['vastEnabled'] = undefined;



  return exports;
}));


