/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdResolutionInfo', 'model/AdRestrictions', 'model/AdSourceRestriction', 'model/ImpressionInfo', 'model/MonetaryRequirementInfo', 'model/PublisherHistoryInfo', 'model/PublisherLocationInfo', 'model/TimeInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AdResolutionInfo'), require('./AdRestrictions'), require('./AdSourceRestriction'), require('./ImpressionInfo'), require('./MonetaryRequirementInfo'), require('./PublisherHistoryInfo'), require('./PublisherLocationInfo'), require('./TimeInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AdRequestVector = factory(root.Dynamix.ApiClient, root.Dynamix.AdResolutionInfo, root.Dynamix.AdRestrictions, root.Dynamix.AdSourceRestriction, root.Dynamix.ImpressionInfo, root.Dynamix.MonetaryRequirementInfo, root.Dynamix.PublisherHistoryInfo, root.Dynamix.PublisherLocationInfo, root.Dynamix.TimeInfo);
  }
}(this, function(ApiClient, AdResolutionInfo, AdRestrictions, AdSourceRestriction, ImpressionInfo, MonetaryRequirementInfo, PublisherHistoryInfo, PublisherLocationInfo, TimeInfo) {
  'use strict';




  /**
   * The AdRequestVector model module.
   * @module model/AdRequestVector
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>AdRequestVector</code>.
   * @alias module:model/AdRequestVector
   * @class
   * @param adSizeInfo {module:model/AdResolutionInfo} 
   * @param adRestrictions {module:model/AdRestrictions} 
   * @param publisherLocationInfo {module:model/PublisherLocationInfo} 
   * @param timeInfo {module:model/TimeInfo} 
   * @param publisherHistoryInfo {module:model/PublisherHistoryInfo} 
   * @param monetaryRequirementInfo {module:model/MonetaryRequirementInfo} 
   * @param publisherRid {String} 
   */
  var exports = function(adSizeInfo, adRestrictions, publisherLocationInfo, timeInfo, publisherHistoryInfo, monetaryRequirementInfo, publisherRid) {
    var _this = this;

    _this['adSizeInfo'] = adSizeInfo;
    _this['adRestrictions'] = adRestrictions;
    _this['publisherLocationInfo'] = publisherLocationInfo;
    _this['timeInfo'] = timeInfo;
    _this['publisherHistoryInfo'] = publisherHistoryInfo;
    _this['monetaryRequirementInfo'] = monetaryRequirementInfo;



    _this['publisherRid'] = publisherRid;
  };

  /**
   * Constructs a <code>AdRequestVector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdRequestVector} obj Optional instance to populate.
   * @return {module:model/AdRequestVector} The populated <code>AdRequestVector</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('adSizeInfo')) {
        obj['adSizeInfo'] = AdResolutionInfo.constructFromObject(data['adSizeInfo']);
      }
      if (data.hasOwnProperty('adRestrictions')) {
        obj['adRestrictions'] = AdRestrictions.constructFromObject(data['adRestrictions']);
      }
      if (data.hasOwnProperty('publisherLocationInfo')) {
        obj['publisherLocationInfo'] = PublisherLocationInfo.constructFromObject(data['publisherLocationInfo']);
      }
      if (data.hasOwnProperty('timeInfo')) {
        obj['timeInfo'] = TimeInfo.constructFromObject(data['timeInfo']);
      }
      if (data.hasOwnProperty('publisherHistoryInfo')) {
        obj['publisherHistoryInfo'] = PublisherHistoryInfo.constructFromObject(data['publisherHistoryInfo']);
      }
      if (data.hasOwnProperty('monetaryRequirementInfo')) {
        obj['monetaryRequirementInfo'] = MonetaryRequirementInfo.constructFromObject(data['monetaryRequirementInfo']);
      }
      if (data.hasOwnProperty('impressionInfo')) {
        obj['impressionInfo'] = ImpressionInfo.constructFromObject(data['impressionInfo']);
      }
      if (data.hasOwnProperty('internetInfo')) {
        obj['internetInfo'] = ApiClient.convertToType(data['internetInfo'], 'String');
      }
      if (data.hasOwnProperty('adSourceRestrictions')) {
        obj['adSourceRestrictions'] = AdSourceRestriction.constructFromObject(data['adSourceRestrictions']);
      }
      if (data.hasOwnProperty('publisherRid')) {
        obj['publisherRid'] = ApiClient.convertToType(data['publisherRid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AdResolutionInfo} adSizeInfo
   */
  exports.prototype['adSizeInfo'] = undefined;
  /**
   * @member {module:model/AdRestrictions} adRestrictions
   */
  exports.prototype['adRestrictions'] = undefined;
  /**
   * @member {module:model/PublisherLocationInfo} publisherLocationInfo
   */
  exports.prototype['publisherLocationInfo'] = undefined;
  /**
   * @member {module:model/TimeInfo} timeInfo
   */
  exports.prototype['timeInfo'] = undefined;
  /**
   * @member {module:model/PublisherHistoryInfo} publisherHistoryInfo
   */
  exports.prototype['publisherHistoryInfo'] = undefined;
  /**
   * @member {module:model/MonetaryRequirementInfo} monetaryRequirementInfo
   */
  exports.prototype['monetaryRequirementInfo'] = undefined;
  /**
   * @member {module:model/ImpressionInfo} impressionInfo
   */
  exports.prototype['impressionInfo'] = undefined;
  /**
   * @member {module:model/AdRequestVector.InternetInfoEnum} internetInfo
   */
  exports.prototype['internetInfo'] = undefined;
  /**
   * @member {module:model/AdSourceRestriction} adSourceRestrictions
   */
  exports.prototype['adSourceRestrictions'] = undefined;
  /**
   * @member {String} publisherRid
   */
  exports.prototype['publisherRid'] = undefined;


  /**
   * Allowed values for the <code>internetInfo</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InternetInfoEnum = {
    /**
     * value: "STRONG"
     * @const
     */
    "STRONG": "STRONG",
    /**
     * value: "AVERAGE"
     * @const
     */
    "AVERAGE": "AVERAGE",
    /**
     * value: "WEAK"
     * @const
     */
    "WEAK": "WEAK"  };


  return exports;
}));


