/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AdSourceRestriction = factory(root.Dynamix.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AdSourceRestriction model module.
   * @module model/AdSourceRestriction
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>AdSourceRestriction</code>.
   * @alias module:model/AdSourceRestriction
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AdSourceRestriction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdSourceRestriction} obj Optional instance to populate.
   * @return {module:model/AdSourceRestriction} The populated <code>AdSourceRestriction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('adSourceRids')) {
        obj['adSourceRids'] = ApiClient.convertToType(data['adSourceRids'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} adSourceRids
   */
  exports.prototype['adSourceRids'] = undefined;



  return exports;
}));


