/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Currency'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Currency'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AotCreditGrant = factory(root.Dynamix.ApiClient, root.Dynamix.Currency);
  }
}(this, function(ApiClient, Currency) {
  'use strict';




  /**
   * The AotCreditGrant model module.
   * @module model/AotCreditGrant
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>AotCreditGrant</code>.
   * @alias module:model/AotCreditGrant
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AotCreditGrant</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AotCreditGrant} obj Optional instance to populate.
   * @return {module:model/AotCreditGrant} The populated <code>AotCreditGrant</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('totalInCents')) {
        obj['totalInCents'] = ApiClient.convertToType(data['totalInCents'], 'Number');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = Currency.constructFromObject(data['currency']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} totalInCents
   */
  exports.prototype['totalInCents'] = undefined;
  /**
   * @member {module:model/Currency} currency
   */
  exports.prototype['currency'] = undefined;



  return exports;
}));


