/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PagedRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PagedRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.CatalogItemPagedRequest = factory(root.Dynamix.ApiClient, root.Dynamix.PagedRequest);
  }
}(this, function(ApiClient, PagedRequest) {
  'use strict';




  /**
   * The CatalogItemPagedRequest model module.
   * @module model/CatalogItemPagedRequest
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>CatalogItemPagedRequest</code>.
   * @alias module:model/CatalogItemPagedRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CatalogItemPagedRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogItemPagedRequest} obj Optional instance to populate.
   * @return {module:model/CatalogItemPagedRequest} The populated <code>CatalogItemPagedRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('itemRids')) {
        obj['itemRids'] = ApiClient.convertToType(data['itemRids'], ['String']);
      }
      if (data.hasOwnProperty('request')) {
        obj['request'] = PagedRequest.constructFromObject(data['request']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} itemRids
   */
  exports.prototype['itemRids'] = undefined;
  /**
   * @member {module:model/PagedRequest} request
   */
  exports.prototype['request'] = undefined;



  return exports;
}));


