/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.CatalogItem = factory(root.Dynamix.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CatalogItem model module.
   * @module model/CatalogItem
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>CatalogItem</code>.
   * @alias module:model/CatalogItem
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>CatalogItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CatalogItem} obj Optional instance to populate.
   * @return {module:model/CatalogItem} The populated <code>CatalogItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('adapterVersion')) {
        obj['adapterVersion'] = ApiClient.convertToType(data['adapterVersion'], 'String');
      }
      if (data.hasOwnProperty('dynamixVersion')) {
        obj['dynamixVersion'] = ApiClient.convertToType(data['dynamixVersion'], 'String');
      }
      if (data.hasOwnProperty('homePage')) {
        obj['homePage'] = ApiClient.convertToType(data['homePage'], 'String');
      }
      if (data.hasOwnProperty('authorEmail')) {
        obj['authorEmail'] = ApiClient.convertToType(data['authorEmail'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} adapterVersion
   */
  exports.prototype['adapterVersion'] = undefined;
  /**
   * @member {String} dynamixVersion
   */
  exports.prototype['dynamixVersion'] = undefined;
  /**
   * @member {String} homePage
   */
  exports.prototype['homePage'] = undefined;
  /**
   * @member {String} authorEmail
   */
  exports.prototype['authorEmail'] = undefined;
  /**
   * @member {module:model/CatalogItem.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "RANKER"
     * @const
     */
    "RANKER": "RANKER",
    /**
     * value: "CONTENTPROVIDER"
     * @const
     */
    "CONTENTPROVIDER": "CONTENTPROVIDER",
    /**
     * value: "CONSTRAINTPROVIDER"
     * @const
     */
    "CONSTRAINTPROVIDER": "CONSTRAINTPROVIDER"  };


  return exports;
}));


