/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DateBoundedTimeRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DateBoundedTimeRange'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.ContentRequest = factory(root.Dynamix.ApiClient, root.Dynamix.DateBoundedTimeRange);
  }
}(this, function(ApiClient, DateBoundedTimeRange) {
  'use strict';




  /**
   * The ContentRequest model module.
   * @module model/ContentRequest
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>ContentRequest</code>.
   * @alias module:model/ContentRequest
   * @class
   * @param timeRanges {Array.<module:model/DateBoundedTimeRange>} 
   * @param publisherRids {Array.<String>} 
   * @param fileRid {String} 
   */
  var exports = function(timeRanges, publisherRids, fileRid) {
    var _this = this;

    _this['timeRanges'] = timeRanges;
    _this['publisherRids'] = publisherRids;
    _this['fileRid'] = fileRid;
  };

  /**
   * Constructs a <code>ContentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentRequest} obj Optional instance to populate.
   * @return {module:model/ContentRequest} The populated <code>ContentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timeRanges')) {
        obj['timeRanges'] = ApiClient.convertToType(data['timeRanges'], [DateBoundedTimeRange]);
      }
      if (data.hasOwnProperty('publisherRids')) {
        obj['publisherRids'] = ApiClient.convertToType(data['publisherRids'], ['String']);
      }
      if (data.hasOwnProperty('fileRid')) {
        obj['fileRid'] = ApiClient.convertToType(data['fileRid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/DateBoundedTimeRange>} timeRanges
   */
  exports.prototype['timeRanges'] = undefined;
  /**
   * @member {Array.<String>} publisherRids
   */
  exports.prototype['publisherRids'] = undefined;
  /**
   * @member {String} fileRid
   */
  exports.prototype['fileRid'] = undefined;



  return exports;
}));


