/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DayBoundedTimeRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DayBoundedTimeRange'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.DateBoundedTimeRange = factory(root.Dynamix.ApiClient, root.Dynamix.DayBoundedTimeRange);
  }
}(this, function(ApiClient, DayBoundedTimeRange) {
  'use strict';




  /**
   * The DateBoundedTimeRange model module.
   * @module model/DateBoundedTimeRange
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>DateBoundedTimeRange</code>.
   * @alias module:model/DateBoundedTimeRange
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DateBoundedTimeRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DateBoundedTimeRange} obj Optional instance to populate.
   * @return {module:model/DateBoundedTimeRange} The populated <code>DateBoundedTimeRange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'String');
      }
      if (data.hasOwnProperty('dayBoundedTimeRange')) {
        obj['dayBoundedTimeRange'] = DayBoundedTimeRange.constructFromObject(data['dayBoundedTimeRange']);
      }
    }
    return obj;
  }

  /**
   * @member {String} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {String} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * @member {module:model/DayBoundedTimeRange} dayBoundedTimeRange
   */
  exports.prototype['dayBoundedTimeRange'] = undefined;



  return exports;
}));


