/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ad'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Ad'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.KeyedAd = factory(root.Dynamix.ApiClient, root.Dynamix.Ad);
  }
}(this, function(ApiClient, Ad) {
  'use strict';




  /**
   * The KeyedAd model module.
   * @module model/KeyedAd
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>KeyedAd</code>.
   * @alias module:model/KeyedAd
   * @class
   * @param ad {module:model/Ad} 
   * @param rid {String} 
   */
  var exports = function(ad, rid) {
    var _this = this;

    _this['ad'] = ad;
    _this['rid'] = rid;
  };

  /**
   * Constructs a <code>KeyedAd</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KeyedAd} obj Optional instance to populate.
   * @return {module:model/KeyedAd} The populated <code>KeyedAd</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ad')) {
        obj['ad'] = Ad.constructFromObject(data['ad']);
      }
      if (data.hasOwnProperty('rid')) {
        obj['rid'] = ApiClient.convertToType(data['rid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Ad} ad
   */
  exports.prototype['ad'] = undefined;
  /**
   * @member {String} rid
   */
  exports.prototype['rid'] = undefined;



  return exports;
}));


