/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.PagedSearchQuery = factory(root.Dynamix.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PagedSearchQuery model module.
   * @module model/PagedSearchQuery
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>PagedSearchQuery</code>.
   * @alias module:model/PagedSearchQuery
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PagedSearchQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PagedSearchQuery} obj Optional instance to populate.
   * @return {module:model/PagedSearchQuery} The populated <code>PagedSearchQuery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('rawQuery')) {
        obj['rawQuery'] = ApiClient.convertToType(data['rawQuery'], 'String');
      }
      if (data.hasOwnProperty('startIndex')) {
        obj['startIndex'] = ApiClient.convertToType(data['startIndex'], 'Number');
      }
      if (data.hasOwnProperty('pageSize')) {
        obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PagedSearchQuery.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} rawQuery
   */
  exports.prototype['rawQuery'] = undefined;
  /**
   * @member {Number} startIndex
   */
  exports.prototype['startIndex'] = undefined;
  /**
   * @member {Number} pageSize
   */
  exports.prototype['pageSize'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "RANKER"
     * @const
     */
    "RANKER": "RANKER",
    /**
     * value: "CONTENTPROVIDER"
     * @const
     */
    "CONTENTPROVIDER": "CONTENTPROVIDER",
    /**
     * value: "CONSTRAINTPROVIDER"
     * @const
     */
    "CONSTRAINTPROVIDER": "CONSTRAINTPROVIDER"  };


  return exports;
}));


