/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KeyedItemObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KeyedItemObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.PagedResponseContentRequest = factory(root.Dynamix.ApiClient, root.Dynamix.KeyedItemObject);
  }
}(this, function(ApiClient, KeyedItemObject) {
  'use strict';




  /**
   * The PagedResponseContentRequest model module.
   * @module model/PagedResponseContentRequest
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>PagedResponseContentRequest</code>.
   * @alias module:model/PagedResponseContentRequest
   * @class
   * @param items {Array.<module:model/KeyedItemObject>} 
   * @param nextStartIndex {Number} 
   * @param requestPageSize {Number} 
   */
  var exports = function(items, nextStartIndex, requestPageSize) {
    var _this = this;

    _this['items'] = items;
    _this['nextStartIndex'] = nextStartIndex;
    _this['requestPageSize'] = requestPageSize;
  };

  /**
   * Constructs a <code>PagedResponseContentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PagedResponseContentRequest} obj Optional instance to populate.
   * @return {module:model/PagedResponseContentRequest} The populated <code>PagedResponseContentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [KeyedItemObject]);
      }
      if (data.hasOwnProperty('nextStartIndex')) {
        obj['nextStartIndex'] = ApiClient.convertToType(data['nextStartIndex'], 'Number');
      }
      if (data.hasOwnProperty('requestPageSize')) {
        obj['requestPageSize'] = ApiClient.convertToType(data['requestPageSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/KeyedItemObject>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {Number} nextStartIndex
   */
  exports.prototype['nextStartIndex'] = undefined;
  /**
   * @member {Number} requestPageSize
   */
  exports.prototype['requestPageSize'] = undefined;



  return exports;
}));


