/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ad', 'model/ImpressionsValidationData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Ad'), require('./ImpressionsValidationData'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.PopRequest = factory(root.Dynamix.ApiClient, root.Dynamix.Ad, root.Dynamix.ImpressionsValidationData);
  }
}(this, function(ApiClient, Ad, ImpressionsValidationData) {
  'use strict';




  /**
   * The PopRequest model module.
   * @module model/PopRequest
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>PopRequest</code>.
   * @alias module:model/PopRequest
   * @class
   * @param ad {module:model/Ad} 
   * @param playTime {Number} 
   * @param impressionsData {module:model/ImpressionsValidationData} 
   */
  var exports = function(ad, playTime, impressionsData) {
    var _this = this;

    _this['ad'] = ad;
    _this['playTime'] = playTime;
    _this['impressionsData'] = impressionsData;
  };

  /**
   * Constructs a <code>PopRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PopRequest} obj Optional instance to populate.
   * @return {module:model/PopRequest} The populated <code>PopRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ad')) {
        obj['ad'] = Ad.constructFromObject(data['ad']);
      }
      if (data.hasOwnProperty('playTime')) {
        obj['playTime'] = ApiClient.convertToType(data['playTime'], 'Number');
      }
      if (data.hasOwnProperty('impressionsData')) {
        obj['impressionsData'] = ImpressionsValidationData.constructFromObject(data['impressionsData']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Ad} ad
   */
  exports.prototype['ad'] = undefined;
  /**
   * @member {Number} playTime
   */
  exports.prototype['playTime'] = undefined;
  /**
   * @member {module:model/ImpressionsValidationData} impressionsData
   */
  exports.prototype['impressionsData'] = undefined;



  return exports;
}));


