/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ReleasedAd'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ReleasedAd'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.PublisherHistoryInfo = factory(root.Dynamix.ApiClient, root.Dynamix.ReleasedAd);
  }
}(this, function(ApiClient, ReleasedAd) {
  'use strict';




  /**
   * The PublisherHistoryInfo model module.
   * @module model/PublisherHistoryInfo
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>PublisherHistoryInfo</code>.
   * @alias module:model/PublisherHistoryInfo
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PublisherHistoryInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublisherHistoryInfo} obj Optional instance to populate.
   * @return {module:model/PublisherHistoryInfo} The populated <code>PublisherHistoryInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('adHistory')) {
        obj['adHistory'] = ApiClient.convertToType(data['adHistory'], [ReleasedAd]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ReleasedAd>} adHistory
   */
  exports.prototype['adHistory'] = undefined;



  return exports;
}));


