/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdRequestWeights', 'model/AdResolutionInfo', 'model/AdRestrictions', 'model/AdSourceRestriction', 'model/DayBoundedTimeRange', 'model/ImpressionInfo', 'model/MonetaryRequirementInfo', 'model/PublisherLocationInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AdRequestWeights'), require('./AdResolutionInfo'), require('./AdRestrictions'), require('./AdSourceRestriction'), require('./DayBoundedTimeRange'), require('./ImpressionInfo'), require('./MonetaryRequirementInfo'), require('./PublisherLocationInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.Publisher = factory(root.Dynamix.ApiClient, root.Dynamix.AdRequestWeights, root.Dynamix.AdResolutionInfo, root.Dynamix.AdRestrictions, root.Dynamix.AdSourceRestriction, root.Dynamix.DayBoundedTimeRange, root.Dynamix.ImpressionInfo, root.Dynamix.MonetaryRequirementInfo, root.Dynamix.PublisherLocationInfo);
  }
}(this, function(ApiClient, AdRequestWeights, AdResolutionInfo, AdRestrictions, AdSourceRestriction, DayBoundedTimeRange, ImpressionInfo, MonetaryRequirementInfo, PublisherLocationInfo) {
  'use strict';




  /**
   * The Publisher model module.
   * @module model/Publisher
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>Publisher</code>.
   * @alias module:model/Publisher
   * @class
   * @param adSizeInfo {module:model/AdResolutionInfo} 
   * @param adRestrictions {module:model/AdRestrictions} 
   * @param publisherLocationInfo {module:model/PublisherLocationInfo} 
   * @param monetaryRequirementInfo {module:model/MonetaryRequirementInfo} 
   * @param publisherEngine {module:model/Publisher.PublisherEngineEnum} 
   * @param weightVector {module:model/AdRequestWeights} 
   */
  var exports = function(adSizeInfo, adRestrictions, publisherLocationInfo, monetaryRequirementInfo, publisherEngine, weightVector) {
    var _this = this;

    _this['adSizeInfo'] = adSizeInfo;
    _this['adRestrictions'] = adRestrictions;
    _this['publisherLocationInfo'] = publisherLocationInfo;

    _this['monetaryRequirementInfo'] = monetaryRequirementInfo;


    _this['publisherEngine'] = publisherEngine;
    _this['weightVector'] = weightVector;


  };

  /**
   * Constructs a <code>Publisher</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Publisher} obj Optional instance to populate.
   * @return {module:model/Publisher} The populated <code>Publisher</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('adSizeInfo')) {
        obj['adSizeInfo'] = AdResolutionInfo.constructFromObject(data['adSizeInfo']);
      }
      if (data.hasOwnProperty('adRestrictions')) {
        obj['adRestrictions'] = AdRestrictions.constructFromObject(data['adRestrictions']);
      }
      if (data.hasOwnProperty('publisherLocationInfo')) {
        obj['publisherLocationInfo'] = PublisherLocationInfo.constructFromObject(data['publisherLocationInfo']);
      }
      if (data.hasOwnProperty('playTimes')) {
        obj['playTimes'] = ApiClient.convertToType(data['playTimes'], [DayBoundedTimeRange]);
      }
      if (data.hasOwnProperty('monetaryRequirementInfo')) {
        obj['monetaryRequirementInfo'] = MonetaryRequirementInfo.constructFromObject(data['monetaryRequirementInfo']);
      }
      if (data.hasOwnProperty('impressionInfo')) {
        obj['impressionInfo'] = ImpressionInfo.constructFromObject(data['impressionInfo']);
      }
      if (data.hasOwnProperty('internetInfo')) {
        obj['internetInfo'] = ApiClient.convertToType(data['internetInfo'], 'String');
      }
      if (data.hasOwnProperty('publisherEngine')) {
        obj['publisherEngine'] = ApiClient.convertToType(data['publisherEngine'], 'String');
      }
      if (data.hasOwnProperty('weightVector')) {
        obj['weightVector'] = AdRequestWeights.constructFromObject(data['weightVector']);
      }
      if (data.hasOwnProperty('remoteEvaluator')) {
        obj['remoteEvaluator'] = ApiClient.convertToType(data['remoteEvaluator'], 'String');
      }
      if (data.hasOwnProperty('adSourceRestrictions')) {
        obj['adSourceRestrictions'] = AdSourceRestriction.constructFromObject(data['adSourceRestrictions']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AdResolutionInfo} adSizeInfo
   */
  exports.prototype['adSizeInfo'] = undefined;
  /**
   * @member {module:model/AdRestrictions} adRestrictions
   */
  exports.prototype['adRestrictions'] = undefined;
  /**
   * @member {module:model/PublisherLocationInfo} publisherLocationInfo
   */
  exports.prototype['publisherLocationInfo'] = undefined;
  /**
   * @member {Array.<module:model/DayBoundedTimeRange>} playTimes
   */
  exports.prototype['playTimes'] = undefined;
  /**
   * @member {module:model/MonetaryRequirementInfo} monetaryRequirementInfo
   */
  exports.prototype['monetaryRequirementInfo'] = undefined;
  /**
   * @member {module:model/ImpressionInfo} impressionInfo
   */
  exports.prototype['impressionInfo'] = undefined;
  /**
   * @member {module:model/Publisher.InternetInfoEnum} internetInfo
   */
  exports.prototype['internetInfo'] = undefined;
  /**
   * @member {module:model/Publisher.PublisherEngineEnum} publisherEngine
   */
  exports.prototype['publisherEngine'] = undefined;
  /**
   * @member {module:model/AdRequestWeights} weightVector
   */
  exports.prototype['weightVector'] = undefined;
  /**
   * @member {String} remoteEvaluator
   */
  exports.prototype['remoteEvaluator'] = undefined;
  /**
   * @member {module:model/AdSourceRestriction} adSourceRestrictions
   */
  exports.prototype['adSourceRestrictions'] = undefined;


  /**
   * Allowed values for the <code>internetInfo</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InternetInfoEnum = {
    /**
     * value: "STRONG"
     * @const
     */
    "STRONG": "STRONG",
    /**
     * value: "AVERAGE"
     * @const
     */
    "AVERAGE": "AVERAGE",
    /**
     * value: "WEAK"
     * @const
     */
    "WEAK": "WEAK"  };

  /**
   * Allowed values for the <code>publisherEngine</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PublisherEngineEnum = {
    /**
     * value: "DEFAULT"
     * @const
     */
    "DEFAULT": "DEFAULT",
    /**
     * value: "REMOTE"
     * @const
     */
    "REMOTE": "REMOTE"  };


  return exports;
}));


