/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdRequestVector', 'model/KeyedAd'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AdRequestVector'), require('./KeyedAd'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.SoftConstraintRequest = factory(root.Dynamix.ApiClient, root.Dynamix.AdRequestVector, root.Dynamix.KeyedAd);
  }
}(this, function(ApiClient, AdRequestVector, KeyedAd) {
  'use strict';




  /**
   * The SoftConstraintRequest model module.
   * @module model/SoftConstraintRequest
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>SoftConstraintRequest</code>.
   * @alias module:model/SoftConstraintRequest
   * @class
   * @param vector {module:model/AdRequestVector} 
   * @param adList {Array.<module:model/KeyedAd>} 
   */
  var exports = function(vector, adList) {
    var _this = this;

    _this['vector'] = vector;
    _this['adList'] = adList;
  };

  /**
   * Constructs a <code>SoftConstraintRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SoftConstraintRequest} obj Optional instance to populate.
   * @return {module:model/SoftConstraintRequest} The populated <code>SoftConstraintRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('vector')) {
        obj['vector'] = AdRequestVector.constructFromObject(data['vector']);
      }
      if (data.hasOwnProperty('adList')) {
        obj['adList'] = ApiClient.convertToType(data['adList'], [KeyedAd]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AdRequestVector} vector
   */
  exports.prototype['vector'] = undefined;
  /**
   * @member {Array.<module:model/KeyedAd>} adList
   */
  exports.prototype['adList'] = undefined;



  return exports;
}));


