/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DayBoundedTimeRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DayBoundedTimeRange'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.TimeInfo = factory(root.Dynamix.ApiClient, root.Dynamix.DayBoundedTimeRange);
  }
}(this, function(ApiClient, DayBoundedTimeRange) {
  'use strict';




  /**
   * The TimeInfo model module.
   * @module model/TimeInfo
   * @version v0.1.0
   */

  /**
   * Constructs a new <code>TimeInfo</code>.
   * @alias module:model/TimeInfo
   * @class
   * @param scheduledPlayTime {Number} 
   */
  var exports = function(scheduledPlayTime) {
    var _this = this;

    _this['scheduledPlayTime'] = scheduledPlayTime;

  };

  /**
   * Constructs a <code>TimeInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TimeInfo} obj Optional instance to populate.
   * @return {module:model/TimeInfo} The populated <code>TimeInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('scheduledPlayTime')) {
        obj['scheduledPlayTime'] = ApiClient.convertToType(data['scheduledPlayTime'], 'Number');
      }
      if (data.hasOwnProperty('playTimes')) {
        obj['playTimes'] = ApiClient.convertToType(data['playTimes'], [DayBoundedTimeRange]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} scheduledPlayTime
   */
  exports.prototype['scheduledPlayTime'] = undefined;
  /**
   * @member {Array.<module:model/DayBoundedTimeRange>} playTimes
   */
  exports.prototype['playTimes'] = undefined;



  return exports;
}));


