/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdRequestVector', 'model/Publisher'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AdRequestVector'), require('../model/Publisher'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.AdConstraintApi = factory(root.Dynamix.ApiClient, root.Dynamix.AdRequestVector, root.Dynamix.Publisher);
  }
}(this, function(ApiClient, AdRequestVector, Publisher) {
  'use strict';

  /**
   * AdConstraint service.
   * @module api/AdConstraintApi
   * @version v0.1.0
   */

  /**
   * Constructs a new AdConstraintApi. 
   * @alias module:api/AdConstraintApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getConstraints operation.
     * @callback module:api/AdConstraintApi~getConstraintsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AdRequestVector} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AdConstraintResource - GetVector
     * Produces the ad request vector with all the constraints provided by the engine and publisher.
     * @param {String} authToken 
     * @param {String} namespace 
     * @param {String} publisherRid 
     * @param {module:model/Publisher} body 
     * @param {module:api/AdConstraintApi~getConstraintsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdRequestVector}
     */
    this.getConstraints = function(authToken, namespace, publisherRid, body, callback) {
      var postBody = body;

      // verify the required parameter 'authToken' is set
      if (authToken === undefined || authToken === null) {
        throw new Error("Missing the required parameter 'authToken' when calling getConstraints");
      }

      // verify the required parameter 'namespace' is set
      if (namespace === undefined || namespace === null) {
        throw new Error("Missing the required parameter 'namespace' when calling getConstraints");
      }

      // verify the required parameter 'publisherRid' is set
      if (publisherRid === undefined || publisherRid === null) {
        throw new Error("Missing the required parameter 'publisherRid' when calling getConstraints");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling getConstraints");
      }


      var pathParams = {
      };
      var queryParams = {
        'publisherRid': publisherRid,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Auth-token': authToken,
        'namespace': namespace
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AdRequestVector;

      return this.apiClient.callApi(
        '/constraints', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
