/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImpressionsValidationData', 'model/ReleasedAd'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ImpressionsValidationData'), require('../model/ReleasedAd'));
  } else {
    // Browser globals (root is window)
    if (!root.Dynamix) {
      root.Dynamix = {};
    }
    root.Dynamix.DeliveryApi = factory(root.Dynamix.ApiClient, root.Dynamix.ImpressionsValidationData, root.Dynamix.ReleasedAd);
  }
}(this, function(ApiClient, ImpressionsValidationData, ReleasedAd) {
  'use strict';

  /**
   * Delivery service.
   * @module api/DeliveryApi
   * @version v0.1.0
   */

  /**
   * Constructs a new DeliveryApi. 
   * @alias module:api/DeliveryApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getNextAd operation.
     * @callback module:api/DeliveryApi~getNextAdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReleasedAd} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get next Ad
     * 
     * @param {String} authToken 
     * @param {String} namespace 
     * @param {String} publisherRid 
     * @param {module:api/DeliveryApi~getNextAdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ReleasedAd}
     */
    this.getNextAd = function(authToken, namespace, publisherRid, callback) {
      var postBody = null;

      // verify the required parameter 'authToken' is set
      if (authToken === undefined || authToken === null) {
        throw new Error("Missing the required parameter 'authToken' when calling getNextAd");
      }

      // verify the required parameter 'namespace' is set
      if (namespace === undefined || namespace === null) {
        throw new Error("Missing the required parameter 'namespace' when calling getNextAd");
      }

      // verify the required parameter 'publisherRid' is set
      if (publisherRid === undefined || publisherRid === null) {
        throw new Error("Missing the required parameter 'publisherRid' when calling getNextAd");
      }


      var pathParams = {
      };
      var queryParams = {
        'publisherRid': publisherRid,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Auth-token': authToken,
        'namespace': namespace
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ReleasedAd;

      return this.apiClient.callApi(
        '/api/delivery', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the popAd operation.
     * @callback module:api/DeliveryApi~popAdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Trigger Proof of Play on Ad
     * 
     * @param {String} authToken 
     * @param {String} namespace 
     * @param {String} publisherRid 
     * @param {String} adRid 
     * @param {module:model/ImpressionsValidationData} body 
     * @param {module:api/DeliveryApi~popAdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.popAd = function(authToken, namespace, publisherRid, adRid, body, callback) {
      var postBody = body;

      // verify the required parameter 'authToken' is set
      if (authToken === undefined || authToken === null) {
        throw new Error("Missing the required parameter 'authToken' when calling popAd");
      }

      // verify the required parameter 'namespace' is set
      if (namespace === undefined || namespace === null) {
        throw new Error("Missing the required parameter 'namespace' when calling popAd");
      }

      // verify the required parameter 'publisherRid' is set
      if (publisherRid === undefined || publisherRid === null) {
        throw new Error("Missing the required parameter 'publisherRid' when calling popAd");
      }

      // verify the required parameter 'adRid' is set
      if (adRid === undefined || adRid === null) {
        throw new Error("Missing the required parameter 'adRid' when calling popAd");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling popAd");
      }


      var pathParams = {
      };
      var queryParams = {
        'publisherRid': publisherRid,
        'adRid': adRid,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Auth-token': authToken,
        'namespace': namespace
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/delivery', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
