/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dynamix);
  }
}(this, function(expect, Dynamix) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dynamix.AdRequestWeights();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdRequestWeights', function() {
    it('should create an instance of AdRequestWeights', function() {
      // uncomment below and update the code to test AdRequestWeights
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be.a(Dynamix.AdRequestWeights);
    });

    it('should have the property adSizeInfo (base name: "adSizeInfo")', function() {
      // uncomment below and update the code to test the property adSizeInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property adRestrictions (base name: "adRestrictions")', function() {
      // uncomment below and update the code to test the property adRestrictions
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property publisherLocationInfo (base name: "publisherLocationInfo")', function() {
      // uncomment below and update the code to test the property publisherLocationInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property timeInfo (base name: "timeInfo")', function() {
      // uncomment below and update the code to test the property timeInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property publisherHistoryInfo (base name: "publisherHistoryInfo")', function() {
      // uncomment below and update the code to test the property publisherHistoryInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property monetaryRequirementInfo (base name: "monetaryRequirementInfo")', function() {
      // uncomment below and update the code to test the property monetaryRequirementInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property impressionInfo (base name: "impressionInfo")', function() {
      // uncomment below and update the code to test the property impressionInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

    it('should have the property internetInfo (base name: "internetInfo")', function() {
      // uncomment below and update the code to test the property internetInfo
      //var instane = new Dynamix.AdRequestWeights();
      //expect(instance).to.be();
    });

  });

}));
