/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dynamix);
  }
}(this, function(expect, Dynamix) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dynamix.CatalogItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CatalogItem', function() {
    it('should create an instance of CatalogItem', function() {
      // uncomment below and update the code to test CatalogItem
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be.a(Dynamix.CatalogItem);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property adapterVersion (base name: "adapterVersion")', function() {
      // uncomment below and update the code to test the property adapterVersion
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property dynamixVersion (base name: "dynamixVersion")', function() {
      // uncomment below and update the code to test the property dynamixVersion
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property homePage (base name: "homePage")', function() {
      // uncomment below and update the code to test the property homePage
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property authorEmail (base name: "authorEmail")', function() {
      // uncomment below and update the code to test the property authorEmail
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Dynamix.CatalogItem();
      //expect(instance).to.be();
    });

  });

}));
