/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dynamix);
  }
}(this, function(expect, Dynamix) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dynamix.CatalogApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CatalogApi', function() {
    describe('createCatalogItem', function() {
      it('should call createCatalogItem successfully', function(done) {
        //uncomment below and update the code to test createCatalogItem
        //instance.createCatalogItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCatalogItem', function() {
      it('should call deleteCatalogItem successfully', function(done) {
        //uncomment below and update the code to test deleteCatalogItem
        //instance.deleteCatalogItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCatalogItem', function() {
      it('should call getCatalogItem successfully', function(done) {
        //uncomment below and update the code to test getCatalogItem
        //instance.getCatalogItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCatalogItems', function() {
      it('should call getCatalogItems successfully', function(done) {
        //uncomment below and update the code to test getCatalogItems
        //instance.getCatalogItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCatalog', function() {
      it('should call listCatalog successfully', function(done) {
        //uncomment below and update the code to test listCatalog
        //instance.listCatalog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCatalog_0', function() {
      it('should call listCatalog_0 successfully', function(done) {
        //uncomment below and update the code to test listCatalog_0
        //instance.listCatalog_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCatalogItem', function() {
      it('should call updateCatalogItem successfully', function(done) {
        //uncomment below and update the code to test updateCatalogItem
        //instance.updateCatalogItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
