/**
 * Dynamix
 * Sign up for Dynamix & grab your token.
 *
 * OpenAPI spec version: v0.1.0
 * Contact: david@theadsontop.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dynamix);
  }
}(this, function(expect, Dynamix) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dynamix.PublisherApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublisherApi', function() {
    describe('bulkResolvePublishers', function() {
      it('should call bulkResolvePublishers successfully', function(done) {
        //uncomment below and update the code to test bulkResolvePublishers
        //instance.bulkResolvePublishers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePublisher', function() {
      it('should call deletePublisher successfully', function(done) {
        //uncomment below and update the code to test deletePublisher
        //instance.deletePublisher(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllAuthorizedPublishers', function() {
      it('should call getAllAuthorizedPublishers successfully', function(done) {
        //uncomment below and update the code to test getAllAuthorizedPublishers
        //instance.getAllAuthorizedPublishers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerPublisher', function() {
      it('should call registerPublisher successfully', function(done) {
        //uncomment below and update the code to test registerPublisher
        //instance.registerPublisher(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePublisher', function() {
      it('should call updatePublisher successfully', function(done) {
        //uncomment below and update the code to test updatePublisher
        //instance.updatePublisher(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
